# -*- coding: utf-8 -*-
"""project 2 decodelabs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUzkLFNr-yClX3aA9V_EkgaBtTuVF5Rn
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Load the Iris benchmark dataset
iris = load_iris()
X, y = iris.data, iris.target

# 2. Split data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

# 3. Apply feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Instantiate and train the KNN model (with K=5)
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, y_train)

# 5. Predict and evaluate the output
predictions = model.predict(X_test_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))
print("\nClassification Report:")
print(classification_report(y_test, predictions, target_names=iris.target_names))